docker-compose-yaml: docker-compose.yml

project: drupal-base

tasks:
  pre-rollout:
    # - run:
    #     name: drush sql-dump
    #     # Takes a pre-rollout backup of production sites only.
    #     command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
    #     service: cli
    #     when: LAGOON_ENVIRONMENT_TYPE=="production"

  post-rollout:

environments:
  main:
    routes:
      - nginx:
        - nginx.main.brittany-route-test-some-long-namespace-name-123.amazeeio.review:
            tls-acme: 'true'
            insecure: Redirect
